apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30007  # Or leave it blank and let Kubernetes assign one
